// Liste des invités pour l'autocomplétion du RSVP (source : Liste_invités_mariage_religieux.xlsx).
// places = nombre total de personnes sur l'invitation (l'invité compris).
// Pour ajouter quelqu'un :  { nom: "Prénom NOM", places: 1 },
const INVITES = [
  { nom: "Laetitia EBA", places: 1 },
  { nom: "Yvan SIELENOU", places: 1 },
  { nom: "Stella CSOH", places: 1 },
  { nom: "Tanguy CSOH", places: 1 },
  { nom: "Ivanna NKWAMOU epse TCHOUATE", places: 1 },
  { nom: "Kevin TCHOUATE", places: 1 },
  { nom: "Kevin KADJI", places: 2 },
  { nom: "Alain Richard BELINGA MEKA", places: 2 },
  { nom: "Océane NGUEMNE", places: 2 },
  { nom: "Alexandre LEMBE", places: 2 },
  { nom: "Steeve HEUNA", places: 1 },
  { nom: "Thierry KETCHEMEN", places: 1 },
  { nom: "Daryl NOUBOM", places: 1 },
  { nom: "Serena NGUEDIA", places: 1 },
  { nom: "Rahim DJUITCHOKO", places: 1 },
  { nom: "Romaric DANGWANG", places: 1 },
  { nom: "Hassan MOHAMAN", places: 1 },
  { nom: "Kenza NGANGOM", places: 1 },
  { nom: "Steve YOUMBI", places: 1 },
  { nom: "Joyce TCHICOU BAYONNE", places: 2 },
  { nom: "Hillary MBIAFEU", places: 2 },
  { nom: "Morgane BEHONH", places: 2 },
  { nom: "Lisa Klara BITHE", places: 1 },
  { nom: "Aicha NZEKET", places: 1 },
  { nom: "Rayan NKENFACK", places: 1 },
  { nom: "Marie-Ange MBALA", places: 1 },
  { nom: "Ulrich MPOULI", places: 1 },
  { nom: "Stephy MONGOUE", places: 2 },
  { nom: "Jules Brice ONANA", places: 1 },
  { nom: "Joel ABANDA", places: 1 },
  { nom: "Laetitia KAMGA", places: 2 },
  { nom: "Fortune MBE", places: 1 },
  { nom: "Ricardo MBE", places: 1 },
  { nom: "Lucien FOUDA", places: 2 },
  { nom: "Géraud DZONGANG", places: 1 },
  { nom: "Glory KENMOGNE", places: 1 },
  { nom: "Claude NOUPA", places: 1 },
  { nom: "Fleurida IMELE epse NOUPA", places: 1 },
  { nom: "Irma TAKAM", places: 1 },
  { nom: "Joel Ebenezer FEUPOSSI", places: 1 },
  { nom: "Joel TIENTCHEU", places: 1 },
  { nom: "Jordan KAPCHE", places: 1 },
  { nom: "Didier FOGWOUNG", places: 1 },
  { nom: "Blondel LEUNDEU", places: 1 },
  { nom: "Rosy LEUNDEU", places: 1 },
  { nom: "Stephane LOGMO", places: 1 },
  { nom: "Carolle MAGNE", places: 1 },
  { nom: "Sandra MBOUMEYANG", places: 1 },
  { nom: "Ninaud DJOMO", places: 1 },
  { nom: "Manu NGNEBA", places: 1 },
  { nom: "Arnold DJOKO", places: 1 },
  { nom: "Cecile NLEMBA", places: 1 },
  { nom: "Serena Noah", places: 2 },
  { nom: "Joyce Sithom", places: 1 },
  { nom: "Mairam TCHIKOU", places: 1 },
  { nom: "Georges TCHIKOU", places: 1 },
  { nom: "Arthur BILONG", places: 1 },
  { nom: "Sonia WANG", places: 1 },
  { nom: "Winnie IKORI", places: 1 },
  { nom: "Indira IKORI", places: 1 },
  { nom: "Elvira NOUBIAP", places: 1 },
  { nom: "Audrey NTAMACK", places: 1 },
  { nom: "Cédric BILLONG", places: 1 },
  { nom: "Denzel", places: 1 },
  { nom: "Stephane NGANGUE", places: 1 },
  { nom: "Claude DJOMGANG", places: 1 },
  { nom: "Robert NGUIMEYA", places: 1 },
  { nom: "Auriol NGUELI EBOUE", places: 1 },
  { nom: "Valère TSAGUE", places: 1 },
  { nom: "Arnold KONO", places: 1 },
  { nom: "Gaetan NZIEBOU", places: 2 },
  { nom: "Ariole MBOGNING", places: 2 },
  { nom: "Maman Nadia", places: 2 },
  { nom: "Yannick OMBETE", places: 1 },
  { nom: "Arthur WOUGNIA", places: 1 },
  { nom: "Juliette NOUBISSIEN", places: 1 },
  { nom: "Ange Estelle TCHELONG", places: 1 },
  { nom: "Jeff TCHELONG", places: 1 },
  { nom: "Daniele FOKO", places: 1 },
  { nom: "Jessica KEMMOGNE", places: 1 },
  { nom: "Chanelle", places: 2 },
  { nom: "Solange MEYING", places: 2 },
  { nom: "Josiane MEYING", places: 3 },
  { nom: "Laure MEYING", places: 5 },
  { nom: "Jeanne MEYING", places: 20 },
  { nom: "Nadine Mireille MEYING", places: 20 },
  { nom: "Marie-Pascale MOUGNOL", places: 3 },
  { nom: "Stéphanie MOUGNOL", places: 3 },
  { nom: "Eddy-Nolan TSALA", places: 1 },
  { nom: "Chloe TSALA", places: 1 },
  { nom: "Emmanuel BOPOUNZA", places: 1 },
  { nom: "Marie-Célia BOPOUNZA", places: 1 },
  { nom: "Inès BOPOUNZA", places: 1 },
  { nom: "Gilles-Axel BOPOUNZA", places: 1 },
  { nom: "Ernestine MINKOULOU", places: 1 },
  { nom: "Jean MINKOULOU", places: 1 },
  { nom: "Christelle", places: 1 },
  { nom: "Bouquet", places: 1 },
  { nom: "Laetitia ONANA", places: 1 },
  { nom: "Espoir ONANA", places: 1 },
  { nom: "Victoire ONANA", places: 1 },
  { nom: "Maman Onana ONANA", places: 1 },
  { nom: "Dany L'Or BAMA", places: 2 },
  { nom: "Gertrude SANAMA", places: 2 },
  { nom: "Gladys BILONG", places: 1 },
  { nom: "Géraldine", places: 2 },
  { nom: "Tata Maguy", places: 1 },
  { nom: "Marie NGNEBA", places: 1 },
  { nom: "Sylvain NGNEBA", places: 1 },
  { nom: "Dimitri NGNEBA", places: 1 },
  { nom: "Christina NGNEBA", places: 1 },
  { nom: "Donald MAMA", places: 1 },
  { nom: "Laure MENGUE", places: 2 },
  { nom: "Léance KANA", places: 1 },
  { nom: "Ulrich ESSI", places: 1 },
  { nom: "Nancy MOLIOGA", places: 2 },
  { nom: "Sarah DIMENE epse MAAH", places: 1 },
  { nom: "Serge MAAH", places: 1 },
  { nom: "Cédric ZANGA", places: 2 },
  { nom: "Diane EDJONGOLO", places: 1 },
  { nom: "Charlène MPONDO", places: 2 },
  { nom: "Ivan FOKO", places: 1 },
  { nom: "Lysarel FONGANG", places: 1 },
  { nom: "Karl TANOUO", places: 1 },
  { nom: "Landry KENGNI", places: 1 },
  { nom: "Audrey TCHUEM", places: 1 },
  { nom: "Anthony NGONO", places: 1 },
  { nom: "Steve DJOUGUELA", places: 1 },
  { nom: "Laetitia GUIZOCK", places: 1 },
  { nom: "Grâce TAMNO", places: 1 },
  { nom: "Karl BOTICH", places: 1 },
  { nom: "Michel NYEBELE", places: 1 },
  { nom: "Emanu NGABA", places: 1 },
  { nom: "Yasmine Lise", places: 2 },
  { nom: "Eric Michel BESSE", places: 1 },
  { nom: "Ryan NGOMO", places: 1 },
  { nom: "Joel ONDJA", places: 2 },
  { nom: "Loic KAMOGNE", places: 1 },
  { nom: "Marc MANGA", places: 1 },
  { nom: "Océane OWONA ESSOMBA", places: 2 },
  { nom: "Ghislain PENDA", places: 1 },
  { nom: "Jasy", places: 2 },
  { nom: "Pascale Lavande ONANA", places: 1 },
  { nom: "Brayan BAMA", places: 1 },
  { nom: "Christiane", places: 1 },
  { nom: "Philip TCHATCHOUA", places: 1 },
  { nom: "Salomé TCHATCHOUA", places: 1 },
  { nom: "Frank BIKOI", places: 1 },
  { nom: "Quincy BIKOI", places: 1 },
  { nom: "Peter WAMBA", places: 1 },
  { nom: "Cindy WAMBA", places: 1 },
  { nom: "Beryanne WANSI", places: 1 },
  { nom: "Jimmy", places: 1 },
  { nom: "Diane MEKANDA", places: 1 },
  { nom: "Manueli DJIPSU", places: 1 },
  { nom: "Nancy DJIPSU", places: 1 },
  { nom: "Jorim CHOKOTE", places: 1 },
  { nom: "Ange-Liz MASSOT", places: 1 },
  { nom: "Donald FOTSING", places: 1 },
  { nom: "Laeticia Kimmy NGOTCHOUA", places: 1 },
  { nom: "Carole EKOLLO", places: 2 },
  { nom: "Safyrha RABIOU", places: 1 },
  { nom: "Alban", places: 1 },
  { nom: "Mark BEHLE", places: 1 },
  { nom: "Anna KANG", places: 1 },
  { nom: "Nelson FOKA", places: 2 },
  { nom: "Nelson NWAHA", places: 1 },
  { nom: "Tanya NWAHA", places: 1 },
  { nom: "Kevin NITCHEU", places: 2 },
  { nom: "Steeve-Alban FOTCHIN", places: 1 },
  { nom: "Valérie KOUNOU", places: 1 },
  { nom: "William NDZANA", places: 1 },
  { nom: "Sylvie LEUKEU", places: 1 },
  { nom: "Arnold ENGOUE", places: 1 },
  { nom: "Jodie ENGOUE", places: 1 },
  { nom: "Rim NGANDJIE", places: 1 },
  { nom: "Marguerite NGANDJIE", places: 1 },
  { nom: "Darrick WAUFO TADIE", places: 1 },
  { nom: "Emma WAUFO TADIE", places: 1 },
  { nom: "Serge WAMBO", places: 2 },
  { nom: "Elsa NANYIM", places: 1 },
  { nom: "Arsène NGUINZASSENGUE", places: 2 },
  { nom: "Steve ELANGA", places: 1 },
  { nom: "Blaise NANA", places: 1 },
  { nom: "Adrien TEMATIO", places: 1 },
  { nom: "Danielle-Ingrid MANDA", places: 1 },
  { nom: "Dominique EYAGA", places: 1 },
  { nom: "Thibaut", places: 1 },
  { nom: "Marcelle EYAGA", places: 1 },
  { nom: "Larissa EYAGA", places: 1 },
  { nom: "Lisa Darlène EBENE", places: 1 },
  { nom: "Yvan PRISO", places: 1 },
  { nom: "Steeve CHIMI", places: 1 },
  { nom: "Jean-Calvin YON BOT", places: 2 },
  { nom: "Annie-Michelle AHANDA", places: 2 },
  { nom: "Honorine ASSIGA", places: 2 },
  { nom: "Will MPOH LOBE", places: 2 },
  { nom: "Jim KENGNE", places: 1 },
  { nom: "Yvan DIPITA", places: 1 },
  { nom: "Sabine (maman de Frank)", places: 2 },
  { nom: "Louis Antoine BILONG", places: 10 },
  { nom: "Charlotte BILONG", places: 10 },
  { nom: "Marie-Hortense NGO NDJIGI", places: 10 },
  { nom: "Louis BILONG", places: 3 },
  { nom: "Louis Boris BILONG", places: 3 },
  { nom: "Mackenzie BILONG", places: 2 },
  { nom: "Théodore BILONG", places: 2 },
  { nom: "Junior ATEBA", places: 2 },
  { nom: "François BILONG", places: 2 },
  { nom: "Adalbert BILONG", places: 2 },
  { nom: "Marguerite POUHE", places: 2 },
  { nom: "Jean-Claude MAKANG", places: 2 },
  { nom: "Gustave MBELLA", places: 2 },
  { nom: "Claudine", places: 2 },
  { nom: "Nicole NGO NDJIGI", places: 2 },
  { nom: "Odile NGO NDJIGI", places: 2 },
  { nom: "Marie Therèse NGO NDJIGI", places: 2 },
  { nom: "Odette NGO NDJIGI", places: 2 },
  { nom: "Paul NDJIGI", places: 2 },
  { nom: "William", places: 1 },
  { nom: "Jeanne NGO MANYIM", places: 1 },
  { nom: "Paola NGO MAKANG", places: 2 },
  { nom: "Rita NGO MAKANG", places: 2 },
  { nom: "Dorcas NGO NDJIGI", places: 2 },
  { nom: "Chouchou NDJIGI", places: 1 },
  { nom: "Père NDJIGI", places: 2 },
  { nom: "Coucou NDJIGI", places: 1 },
  { nom: "Samantha NDJIGI", places: 1 },
  { nom: "Ornella NDJIGI", places: 1 },
  { nom: "Majoie NGO NDJIGI", places: 1 },
  { nom: "Sonia NDJIGI", places: 1 },
  { nom: "Tonton Alain", places: 2 },
  { nom: "Tonton TANG", places: 2 },
  { nom: "Tonton Charles", places: 2 },
  { nom: "Tonton Félix", places: 2 },
  { nom: "Tata Elisabeth", places: 2 },
  { nom: "Famille TSALA", places: 15 },
  { nom: "Amis papa", places: 5 },
];
